name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please provide as much detail as possible.

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of sarif-to-md-rs are you using?
      placeholder: e.g., v0.1.0 or commit hash
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. With input file '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide details about your environment:
      value: |
        - OS: [e.g., Ubuntu 22.04, macOS 14.0, Windows 11]
        - Rust version: [output of `rustc --version`]
        - Installation method: [cargo install, binary download, package manager]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Output/Logs
      description: If applicable, add error messages or log output
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, such as sample SARIF files or configuration.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following:
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the requested information
          required: true
        - label: I am willing to help test a fix if provided
          required: false